# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PCA-morphed_model',
                'doc_host': 'https://Maryam-Sargol.github.io',
                'git_url': 'https://github.com/Maryam-Sargol/PCA-morphed_model',
                'lib_path': 'PCA_morphed_model'},
  'syms': { 'PCA_morphed_model.STD': {'PCA_morphed_model.STD.desired_STD': ('std.html#desired_std', 'PCA_morphed_model/STD.py')},
            'PCA_morphed_model.export_file_mix': { 'PCA_morphed_model.export_file_mix.export_file': ( 'export_file_mix.html#export_file',
                                                                                                      'PCA_morphed_model/export_file_mix.py')},
            'PCA_morphed_model.export_key': { 'PCA_morphed_model.export_key.export_key_file': ( 'export_key.html#export_key_file',
                                                                                                'PCA_morphed_model/export_key.py')},
            'PCA_morphed_model.extract_NSH_stl_key': { 'PCA_morphed_model.extract_NSH_stl_key.extract_nodes_shells_mix_stl_key': ( 'extract_nsh_stl_key.html#extract_nodes_shells_mix_stl_key',
                                                                                                                                   'PCA_morphed_model/extract_NSH_stl_key.py')},
            'PCA_morphed_model.main_pca': {},
            'PCA_morphed_model.pca': {'PCA_morphed_model.pca.run_PCA': ('pca.html#run_pca', 'PCA_morphed_model/pca.py')},
            'PCA_morphed_model.read_extract': { 'PCA_morphed_model.read_extract.read_extract_nodes_shells': ( 'read_extract.html#read_extract_nodes_shells',
                                                                                                              'PCA_morphed_model/read_extract.py')}}}
